<?php

/**
 * @file
 * Contains vercel_deploy.module hooks.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\vercel_deploy\ToolbarHandler;

/**
 * Implements hook_toolbar().
 */
function vercel_deploy_toolbar() {

  return \Drupal::service('class_resolver')
    ->getInstanceFromDefinition(ToolbarHandler::class)
    ->toolbar();
}

/**
 * Implements hook_help().
 */
function vercel_deploy_help(string $route_name, RouteMatchInterface $route_match) {

  switch ($route_name) {
    case 'help.page.vercel_deploy':

      $text = file_get_contents(__DIR__ . "/README.md");
      if (!\Drupal::moduleHandler()->moduleExists('markdown')) {
        return '<pre>' . $text . '</pre>';
      }

      // Use the Markdown filter to render the README.
      $filter_manager = \Drupal::service('plugin.manager.filter');
      $settings       = \Drupal::configFactory()
        ->get('markdown.settings')
        ->getRawData();
      $config         = ['settings' => $settings];
      $filter         = $filter_manager->createInstance('markdown', $config);

      return $filter->process($text, 'en');
  }

  return NULL;
}
