vercel_deploy.settings:
  type: config_object
  label: 'Vercel Deploy settings'
  mapping:
    deploy_hooks_urls:
      type: sequence
      label: 'Vercel Deploy Hooks URLs'
      sequence:
        - type: string
          label: 'Deploy Hooks URL'
